#!/bin/bash
# ===================================================================
# Surflix Setup Helper
# Generate semua secrets + create .env file in one go
# ===================================================================

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo ""
echo -e "${BLUE}🎬 Surflix Setup Helper${NC}"
echo "========================================"
echo ""

# Check if .env already exists
if [ -f ".env" ]; then
  echo -e "${YELLOW}⚠️  .env udah ada. Mau overwrite? (y/N)${NC}"
  read -r answer
  if [ "$answer" != "y" ] && [ "$answer" != "Y" ]; then
    echo "Cancelled."
    exit 0
  fi
  cp .env .env.backup.$(date +%s)
  echo "Backed up old .env"
fi

# Check if .env.example exists
if [ ! -f ".env.example" ]; then
  echo -e "${RED}❌ .env.example gak ditemukan. Lo lagi di folder yang bener kan?${NC}"
  exit 1
fi

# Generate secrets
echo -e "${BLUE}🔐 Generating secrets...${NC}"
SESSION_SECRET=$(openssl rand -base64 32)
WEBHOOK_SECRET=$(openssl rand -hex 32)
echo "✓ SESSION_SECRET generated"
echo "✓ WEBHOOK_SECRET generated"
echo ""

# Admin credentials
echo -e "${BLUE}👤 Admin Setup${NC}"
read -p "Admin username (default: idrus): " ADMIN_USERNAME
ADMIN_USERNAME=${ADMIN_USERNAME:-idrus}

while true; do
  read -sp "Admin password (min 8 karakter): " ADMIN_PASSWORD
  echo
  if [ ${#ADMIN_PASSWORD} -ge 8 ]; then
    break
  fi
  echo -e "${RED}Password kependekan${NC}"
done

# Generate bcrypt hash via Docker
echo -e "${BLUE}🔑 Generating password hash...${NC}"
ADMIN_PASSWORD_HASH=$(docker run --rm node:20-alpine sh -c "npm install bcryptjs --silent 2>/dev/null && node -e \"const b=require('bcryptjs'); b.hash('$ADMIN_PASSWORD', 10).then(h => console.log(h));\"")
echo "✓ Password hash generated"
echo ""

# Jellyseerr
echo -e "${BLUE}🎞️  Jellyseerr Config${NC}"
read -p "Jellyseerr URL (default: http://jellyseerr:5055): " JELLYSEERR_URL
JELLYSEERR_URL=${JELLYSEERR_URL:-http://jellyseerr:5055}
read -p "Jellyseerr API Key: " JELLYSEERR_API_KEY
echo ""

# App URLs
echo -e "${BLUE}🌐 Domain Config${NC}"
read -p "App URL (default: https://request.surdilamak.my.id): " APP_URL
APP_URL=${APP_URL:-https://request.surdilamak.my.id}
read -p "Jellyfin URL (default: https://jellyfin.surdilamak.my.id): " JELLYFIN_URL
JELLYFIN_URL=${JELLYFIN_URL:-https://jellyfin.surdilamak.my.id}
echo ""

# Email
echo -e "${BLUE}📧 Email (Resend)${NC}"
read -p "Resend API Key (re_xxx, leave blank to skip): " RESEND_API_KEY
read -p "Email From (default: 'Surflix <noreply@surdilamak.my.id>'): " EMAIL_FROM
EMAIL_FROM=${EMAIL_FROM:-"Surflix <noreply@surdilamak.my.id>"}
echo ""

# Telegram
echo -e "${BLUE}💬 Telegram Bot${NC}"
read -p "Telegram Bot Token (leave blank to skip): " TELEGRAM_BOT_TOKEN
read -p "Telegram Admin Chat ID: " TELEGRAM_ADMIN_CHAT_ID
echo ""

# Write .env
echo -e "${BLUE}💾 Writing .env...${NC}"
cat > .env <<EOF
# Generated by setup.sh on $(date)

NODE_ENV=production
NEXT_PUBLIC_APP_URL=$APP_URL
NEXT_PUBLIC_APP_NAME=Surflix
NEXT_PUBLIC_JELLYFIN_URL=$JELLYFIN_URL

DATABASE_URL="file:/data/surflix.db"

JELLYSEERR_URL=$JELLYSEERR_URL
JELLYSEERR_API_KEY=$JELLYSEERR_API_KEY

SESSION_SECRET=$SESSION_SECRET
ADMIN_USERNAME=$ADMIN_USERNAME
ADMIN_PASSWORD_HASH='$ADMIN_PASSWORD_HASH'

RESEND_API_KEY=$RESEND_API_KEY
EMAIL_FROM="$EMAIL_FROM"

TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_ADMIN_CHAT_ID=$TELEGRAM_ADMIN_CHAT_ID

RATE_LIMIT_MAX=10
RATE_LIMIT_WINDOW_MS=3600000

WEBHOOK_SECRET=$WEBHOOK_SECRET
EOF

chmod 600 .env

echo ""
echo -e "${GREEN}✅ Setup complete!${NC}"
echo ""
echo "Next steps:"
echo "  1. Review .env (optional): cat .env"
echo "  2. Setup Jellyseerr network (lihat DEPLOYMENT.md Step 5)"
echo "  3. Build & run: docker compose up -d --build"
echo "  4. Check logs: docker compose logs -f surflix"
echo ""
echo -e "${YELLOW}📝 Catat ini buat setup Jellyseerr webhook:${NC}"
echo "  Webhook URL: $APP_URL/api/webhooks/jellyseerr"
echo "  Auth Header: Bearer $WEBHOOK_SECRET"
echo ""
